default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  # TODO: Differentiate between Rails and Sidekiq processes, and use an appropriate value.
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 4) %>
  #port: 5432
  #schema_search_path: myapp,sharedapp,public # The server defaults to $user,public
  #min_messages: notice # Defaults to warning. `debug5`..`debug1`,`log`,`notice`,`warning`,`error`,`fatal`,`panic`

development:
  primary:
    <<: *default
    host: <%= ENV.fetch("CORE_OLTP_DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("CORE_OLTP_DATABASE_PORT", "5432") %>
    database: <%= ENV.fetch("CORE_OLTP_DATABASE_NAME", "core_dev_debug") %>
    username: <%= ENV.fetch("CORE_OLTP_DATABASE_USERNAME", "") %>
    password: <%= ENV.fetch("CORE_OLTP_DATABASE_PASSWORD", "") %>
